In [1]:
import os
from datetime import datetime
import time

import numpy as np
import pandas as pd
from recbole.quick_start import run_recbole
from tqdm import tqdm

In [2]:
from recbole.quick_start import load_data_and_model

In [37]:
model_path='saved/NeuMF-Apr-14-2022_03-42-07.pth'

config, model, dataset, train_data, valid_data, test_data = load_data_and_model(model_path)

14 Apr 03:55    INFO  
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /opt/ml/input/data/recbole
checkpoint_dir = saved
show_progress = False
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 10
train_batch_size = 2048
learner = adam
learning_rate = 0.01
neg_sampling = {'uniform': 1}
eval_step = 1
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [4, 1, 1]}, 'group_by': 'user', 'order': 'TO', 'mode': 'uni50'}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision', 'MAP']
topk = [10]
valid_metric = Recall@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator = 	
seq_separator =  
USER_ID_FIELD = user
ITEM_ID_FIELD = item
RATING_FIELD = rating
TI

### test용으로 NeuMF 적용해보기 (전체 데이터셋말고 일부)

In [39]:
# 테스트 데이터의 일부 가져오기
for i, test_x in enumerate(test_data):
    if i==0:
        t1 = test_x
    if i==1:
        t2 = test_x
        break
    #ininteractionter = data[0]


In [41]:
test_x[0]#.shape

The batch_size of interaction: 1530
    timestamp, torch.Size([1530]), cpu, torch.float32
    user, torch.Size([1530]), cpu, torch.int64
    item, torch.Size([1530]), cpu, torch.int64
    rating, torch.Size([1530]), cpu, torch.float32
    label, torch.Size([1530]), cpu, torch.float32


In [45]:
device = config.final_config_dict['device']
device

device(type='cuda')

In [ ]:
inter = t1[0].to(device)

In [54]:
#확인
inter[model.USER_ID]#.shape

tensor([1, 1, 1,  ..., 1, 1, 1], device='cuda:0')

In [49]:
#확인
inter[model.ITEM_ID]

tensor([ 315,  316,  317,  ..., 4764, 1190, 1931], device='cuda:0')

In [59]:
output = model(inter[model.USER_ID], inter[model.ITEM_ID])
output #user_id가 해당 item_id를 볼 예측 확률 값 -> 전체 데이터셋 만들어 적용하기

tensor([0.2234, 0.1389, 0.6008,  ..., 0.0400, 0.0200, 0.1278], device='cuda:0',
       grad_fn=<SqueezeBackward1>)